<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_geolocation"
 *
 * Auto generated by Extension Builder 2015-08-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'RKW Geolocation',
	'description' => 'Locates addresses and / or zip codes',
	'category' => 'plugin',
    'author' => 'Maximilian Fäßler, Steffen Kroggel, Christian Dilger',
    'author_email' => 'maximilian@faesslerweb.de, developer@steffenkroggel.de, c.dilger@addorange.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'clearCacheOnLoad' => 0,
	'version' => '9.5.1001',
	'constraints' => [
		'depends' => [
			'typo3' => '9.5.0-10.4.99',
            'core_extended' => '9.5.4-10.4.99'
		],
		'conflicts' => [
		],
		'suggests' => [
		],
	],
];
